# SPDX-License-Identifier: MIT
name: CI

on:
  push:
    branches:
    - main

jobs:
  test-386:
    name: Test 32-bit Scoop apps
    runs-on: windows-2019
    steps:
    - name: Set up Scoop
      shell: powershell
      run: |
        iwr -useb get.scoop.sh | iex
        scoop bucket add ffurrer2 https://github.com/ffurrer2/scoop-bucket
        echo "$Env:HOMEDRIVE$Env:HOMEPATH\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test semver installation
      run: |
        scoop install --arch 32bit semver
        semver version

  test-amd64:
    name: Test 64-bit Scoop apps
    runs-on: windows-2019
    steps:
    - name: Set up Scoop
      shell: powershell
      run: |
        iwr -useb get.scoop.sh | iex
        scoop bucket add ffurrer2 https://github.com/ffurrer2/scoop-bucket
        echo "$Env:HOMEDRIVE$Env:HOMEPATH\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test semver installation
      run: |
        scoop install --arch 64bit semver
        semver version
